project:
  type: book
  output-dir: ../docs
  resources:
    - styles.css
    - images

book:
  title: "The collapse of environmental predictability erodes reproductive success in a Tropical seabird"
  title-short: "Phenological Mismatch in a Tropical Predator"
  author:
    - name: Santiago Ortega
    - name: Cristina Rodríguez
    - name: Ayumi Mizuno
    - name: Laura Arroyo
    - name: Hugh Drummond
    - name: Shinichi Nakagawa

  date: last-modified
  date-format: "MMMM D, YYYY"
  cover-image: Sula.JPG
  chapters:
    - index.qmd
    - part: "Main Analysis"
      chapters:
        - 1-bloom-onset.qmd
        - 2-phenological-mismatches.qmd
        - 3-model-fitting.qmd
        - 4-diagnostics.qmd
        - 6-full_summaries.qmd
    - part: "Appendices"
      chapters:
        - sensitivity_blooms.qmd
        - code_figures.qmd
        
  navbar:
    right:
      - icon: github
        href: https://github.com/Santiago-0rtega/Collapse_environmental_predictability_erodes_reproductive_success
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2

number-sections: false 
bibliography: references.bib
biblio-style: apalike

format:
  html:
    theme:
      light: cosmo 
      dark: flatly
    css: styles.css
    mainfont: "Atkinson Hyperlegible"
    fontsize: 1.05em
    linestretch: 1.35
    favicon: images/favicon.png

    toc: true
    toc-depth: 3
    toc-location: left

    code-tools: true
    code-copy: true
    

    link-external-newwindow: true
    smooth-scroll: true

    # nicer citations in browser
    citeproc: true
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 1400px  
      margin-width: 200px
      gutter-width: 1.5rem
execute:
  freeze: auto
  warning: false
  message: false

editor: visual