project:
  type: book
  output-dir: ../docs
  resources:
    - styles.css
    - images

book:
  title: "Declining environmental predictability erodes reproduction in a tropical seabird"
  title-short: "Phenological mismatch in a tropical predator"
  subtitle: "A reproducible analysis website for the Blue-footed Booby project"
  author:
    - name: Santiago Ortega
      url: https://santiago-0rtega.github.io/
      corresponding: true
    - name: Cristina Rodríguez
    - name: Ayumi Mizuno
    - name: Laura Arroyo
    - name: Hugh Drummond
    - name: Shinichi Nakagawa

  date: last-modified
  date-format: "MMMM D, YYYY"
  cover-image: images/sula-web.jpg

  chapters:
    - index.qmd
    - part: "Main analysis"
      chapters:
        - 1-bloom-onset.qmd
        - 2-phenological-mismatches.qmd
        - 3-model-fitting.qmd
        - 4-diagnostics.qmd
        - 6-full_summaries.qmd
    - part: "Appendices"
      chapters:
        - sensitivity_blooms.qmd
        - sensitivity_drop_enso.qmd
        - SI_individual_mismatch_trajectories.qmd
        - estimated-fleds.qmd
        - code_figures.qmd

  navbar:
    pinned: true
    right:
      - text: "GitHub"
        icon: github
        href: https://github.com/Santiago-0rtega/Declining_environmental_predictability_erodes_reproduction_tropical_seabird/
      - text: "References"
        href: references.qmd

  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    pinned: true

  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/Santiago-0rtega/Declining_environmental_predictability_erodes_reproduction_tropical_seabird/
  repo-actions: [source, issue]


number-sections: false

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    include-in-header: fonts-header.html
    mainfont: "Fira Sans"
    fontsize: 1.05em
    linestretch: 1.5
    favicon: images/cossee_logo.png

    toc: true
    toc-depth: 3
    toc-location: left

    code-tools: true
    code-copy: true
    code-overflow: wrap
    code-link: true

    link-external-newwindow: true
    smooth-scroll: true
    anchor-sections: true
    footnotes-hover: true
    citations-hover: true

    page-layout: full
    fig-align: center
    fig-responsive: true

    grid:
      sidebar-width: 300px
      body-width: 1350px
      margin-width: 220px
      gutter-width: 1.5rem

execute:
  freeze: auto
  warning: false
  message: false
  echo: true

editor: visual
